PSG14a emulator: gpio_exti.c File Reference
gpio_exti.c File Reference
Contains GPIO and EXTI HAL functions.
#include "gpio_exti.h"
#include "stm32f0xx.h"
#include <stdint.h>
#include <stddef.h>
Data Structures
struct Gpio_Hal_t
GPIO pin description.
Enumerations
enum Gpio_Mode_t { GPIO_MODE_IN = 0 , GPIO_MODE_OUT }
Here are two modes only: out push/pull and in for button.
Functions
void EXTI4_15_IRQHandler (void)
void Exti_Clear_Pending (void)
void Gpio_Init (void)
void Gpio_Set_Pin (const Gpio_id_t Id)
void Gpio_Reset_Pin (const Gpio_id_t Id)
void Gpio_Reset_all_Outs (void)
uint8_t Gpio_Get_Pin (const Gpio_id_t Id)
Detailed Description
Contains GPIO and EXTI HAL functions.
mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
11-01-2019 Mykhaylo Shcherbak
Version
2.00
Enumeration Type Documentation
Gpio_Mode_t
enum Gpio_Mode_t
Here are two modes only: out push/pull and in for button.
Enumerator
GPIO_MODE_IN
GPIO_MODE_OUT
< Button < Channel or LED
Function Documentation
EXTI4_15_IRQHandler()
void EXTI4_15_IRQHandler (void)
Exti_Clear_Pending()
void Exti_Clear_Pending (void)
Referenced by main(), and Sleep_on().
Gpio_Get_Pin()
uint8_t Gpio_Get_Pin (const Gpio_id_t Id)
References GPIO_MODE_IN, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Gpio_Init()
void Gpio_Init (void)
References GPIO_MODE_IN, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Referenced by main().
Gpio_Reset_all_Outs()
void Gpio_Reset_all_Outs (void)
References GPIO_MODE_OUT, Gpio_Reset_Pin(), and GPIO_TOTAL.
Referenced by Sleep_on().
Gpio_Reset_Pin()
void Gpio_Reset_Pin (const Gpio_id_t Id)
References GPIO_MODE_OUT, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Referenced by Control_Outs(), Gpio_Reset_all_Outs(), and mainCyclePreRun().
Gpio_Set_Pin()
void Gpio_Set_Pin (const Gpio_id_t Id)
References GPIO_MODE_OUT, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Referenced by Control_Outs(), and mainCyclePreRun().