PSG14a emulator: led_control.c File Reference
led_control.c File Reference
Contains led blinking functions.
#include <led_control.h>
#include <stdint.h>
#include "clock_and_timers.h"
#include "led.h"
#include "main_outputs.h"
Data Structures
struct Blink_mode_t
Blink mode config.
Functions
void Blink_Led (void)
Pass-through function for led blinking Blinking is done according to the selected mode using the Blink_mode_t table element.
Detailed Description
Contains led blinking functions.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
02-01-2019
Version
1.00
Function Documentation
Blink_Led()
void Blink_Led (void)
Pass-through function for led blinking Blinking is done according to the selected mode using the Blink_mode_t table element.
This function must be called in main while(1) cycle. It contains internal timers so it may be called at any frequency but the faster it's called, the more precision is got
References Get_State(), IsExpiredTimer(), ResetTimer(), and STATE_IDLE.
Referenced by mainCycleRun().