PSG14a emulator: main_outputs.c File Reference
main_outputs.c File Reference
Contains functions for controlling main outputs.
#include <string.h>
#include <stdint.h>
#include "gpio_exti.h"
#include "main_outputs.h"
#include "control_tables.h"
#include "clock_and_timers.h"
Enumerations
enum Ret_State_t { RET_STATE_OFF = 0 , RET_STATE_ON , RET_STATE_NO_CHANGE }
Functions
State_t Get_State (void)
void Set_State (const State_t NewState)
uint8_t Control_Outs (const uint8_t FirstTime)
Controls outputs for the current time.
Variables
Channel_Step_t Cyclogram_Cold []
Contains a cyclogram for cold start mode.
Channel_Step_t Cyclogram_Start []
Contains a cyclogram for real start mode.
Detailed Description
Contains functions for controlling main outputs.
mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
05-01-2019
Version
1.00
Enumeration Type Documentation
Ret_State_t
enum Ret_State_t
Enumerator
RET_STATE_OFF
RET_STATE_ON
RET_STATE_NO_CHANGE
Function Documentation
Control_Outs()
uint8_t Control_Outs (const uint8_t FirstTime)
Controls outputs for the current time.
Parameters
FirstTime This is first run of the function if nonzero
Returns
non-zero if all sequence is over
References CH_TOTAL, Cyclogram_Cold, Cyclogram_Start, Get_State(), Gpio_Reset_Pin(), Gpio_Set_Pin(), ReadTimer(), ResetTimer(), STATE_COLD, and STATE_START.
Referenced by mainCycleRun().
Get_State()
State_t Get_State (void)
Returns the current device state
Returns
Current state
Referenced by Blink_Led(), Control_Outs(), and main().
Set_State()
void Set_State (const State_t NewState)
Sets the current device state
Parameters
NewState New device state
References STATE_IDLE, and STATE_TOTAL.
Referenced by mainCycleRun().
Variable Documentation
Cyclogram_Cold
Channel_Step_t Cyclogram_Cold[] extern
Contains a cyclogram for cold start mode.
Referenced by Control_Outs().
Cyclogram_Start
Channel_Step_t Cyclogram_Start[] extern
Contains a cyclogram for real start mode.
Referenced by Control_Outs().