PSG14a emulator: main_outputs.h File Reference
main_outputs.h File Reference
Contains functions prototypes for controlling main outputs.
#include <stdint.h>
Enumerations
enum State_t { STATE_IDLE = 0 , STATE_START , STATE_COLD , STATE_TOTAL }
Functions
State_t Get_State (void)
void Set_State (const State_t NewState)
uint8_t Control_Outs (const uint8_t FirstTime)
Controls outputs for the current time.
Detailed Description
Contains functions prototypes for controlling main outputs.
mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
05-01-2019
Version
1.00
Enumeration Type Documentation
State_t
enum State_t
Enumerator
STATE_IDLE
Idle state. Must not occur in real life. In idle CPU sleeps
STATE_START
Starting the engine
STATE_COLD
Starting without fuel
STATE_TOTAL
Total number of states
Function Documentation
Control_Outs()
uint8_t Control_Outs (const uint8_t FirstTime)
Controls outputs for the current time.
Parameters
FirstTime This is first run of the function if nonzero
Returns
non-zero if all sequence is over
References CH_TOTAL, Cyclogram_Cold, Cyclogram_Start, Get_State(), Gpio_Reset_Pin(), Gpio_Set_Pin(), ReadTimer(), ResetTimer(), STATE_COLD, and STATE_START.
Referenced by mainCycleRun().
Get_State()
State_t Get_State (void)
Returns the current device state
Returns
Current state
Referenced by Blink_Led(), Control_Outs(), and main().
Set_State()
void Set_State (const State_t NewState)
Sets the current device state
Parameters
NewState New device state
References STATE_IDLE, and STATE_TOTAL.
Referenced by mainCycleRun().