M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date чт, 19-вер-2024 02:02:44 +0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-19T02:02:44+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X30.0Y-81.0
X110.0Y-45.0
X110.0Y-81.0
M30
