PSG14a emulator: gpio_exti.h File Reference
gpio_exti.h File Reference
Contains GPIO and EXTI hardware abstraction layer prototypes.
#include <stdint.h>
Enumerations
enum Gpio_id_t {
GPIO_CH0 = 0 , GPIO_CH1 , GPIO_CH2 , GPIO_CH3 ,
GPIO_CH4 , GPIO_CH5 , GPIO_CH6 , GPIO_CH7 ,
GPIO_LED , GPIO_BUTTON_START , GPIO_BUTTON_COLD , GPIO_TOTAL
}
enum Buttons_t { BUTTON_NONE = 0 , BUTTON_START , BUTTON_COLD }
Functions
void Gpio_Init (void)
void Gpio_Set_Pin (const Gpio_id_t Id)
void Gpio_Reset_Pin (const Gpio_id_t Id)
void Gpio_Reset_all_Outs (void)
void Exti_Clear_Pending (void)
uint8_t Gpio_Get_Pin (const Gpio_id_t Id)
Detailed Description
Contains GPIO and EXTI hardware abstraction layer prototypes.
mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om Mykhaylo Shcherbak
Date
11-01-2019
Version
2.00
Enumeration Type Documentation
Buttons_t
enum Buttons_t
Enumerator
BUTTON_NONE
BUTTON_START
BUTTON_COLD
Gpio_id_t
enum Gpio_id_t
Enumerator
GPIO_CH0
GPIO_CH1
OUT CH0 (Starter)
GPIO_CH2
OUT CH1 (Priming fuel)
GPIO_CH3
OUT CH2 (Spark plug)
GPIO_CH4
OUT CH3 (TBD)
GPIO_CH5
OUT CH4 (TBD)
GPIO_CH6
OUT CH5 (TBD)
GPIO_CH7
OUT CH6 (TBD)
GPIO_LED
OUT CH7 (TBD)
GPIO_BUTTON_START
Led
GPIO_BUTTON_COLD
Input for start button
GPIO_TOTAL
Input for start_without_fuel button Total number of GPIOs
Function Documentation
Exti_Clear_Pending()
void Exti_Clear_Pending (void)
Referenced by main(), and Sleep_on().
Gpio_Get_Pin()
uint8_t Gpio_Get_Pin (const Gpio_id_t Id)
References GPIO_MODE_IN, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Gpio_Init()
void Gpio_Init (void)
References GPIO_MODE_IN, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Referenced by main().
Gpio_Reset_all_Outs()
void Gpio_Reset_all_Outs (void)
References GPIO_MODE_OUT, Gpio_Reset_Pin(), and GPIO_TOTAL.
Referenced by Sleep_on().
Gpio_Reset_Pin()
void Gpio_Reset_Pin (const Gpio_id_t Id)
References GPIO_MODE_OUT, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Referenced by Control_Outs(), Gpio_Reset_all_Outs(), and mainCyclePreRun().
Gpio_Set_Pin()
void Gpio_Set_Pin (const Gpio_id_t Id)
References GPIO_MODE_OUT, GPIO_TOTAL, Gpio_Hal_t::Mode, Gpio_Hal_t::Pin, and Gpio_Hal_t::port.
Referenced by Control_Outs(), and mainCyclePreRun().