PSG14a emulator: sleep.h File Reference
sleep.h File Reference
Functions
void Sleep_on (void)
Function Documentation
Sleep_on()
void Sleep_on (void)
References Exti_Clear_Pending(), and Gpio_Reset_all_Outs().
Referenced by main().