PSG14a emulator: main_cycle.h File Reference
main_cycle.h File Reference
Contains prototypes of functions that are called in while(1) main cycle and after it.
Functions
void mainCycleRun (void)
This function is called in while(1). Waiting for the end of the tick is done after it.
void mainCyclePreRun (void)
This function is called before main cycle and makes 5s pause to connect debugger if needed.
Detailed Description
Contains prototypes of functions that are called in while(1) main cycle and after it.
Author
Mykhaylo Shcherbak mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Date
03-08-2019
Version
1.00
Function Documentation
mainCyclePreRun()
void mainCyclePreRun (void)
This function is called before main cycle and makes 5s pause to connect debugger if needed.
References GPIO_LED, Gpio_Reset_Pin(), Gpio_Set_Pin(), IsExpiredTimer(), and ResetTimer().
Referenced by main().
mainCycleRun()
void mainCycleRun (void)
This function is called in while(1). Waiting for the end of the tick is done after it.
References Blink_Led(), Buttons_Get_State(), Control_Outs(), MCSM_Cold, MCSM_Emergency_Stop_Cold, MCSM_Emergency_Stop_Start, MCSM_Idle, MCSM_Start, Set_State(), STATE_COLD, STATE_IDLE, and STATE_START.
Referenced by main().