PSG14a emulator: clock_and_timers.h File Reference
clock_and_timers.h File Reference
Contains clocks and timer functions prototypes.
Macros
#define SYSTICK_FREQ 1000
#define CORE_FREQ 8000000
Typedefs
typedef void(* Systick_Callback_t) (void)
Functions
void Clock_HSI_Init (void)
inits HSI as a main clock. PLL will not be used. Core/systick frequency is ~8Mhz
void Systick_Init (const Systick_Callback_t Systick_Callback)
Inits systick timer interrupt for 1ms period.
void ResetTimer (uint32_t *const Timer)
Resets software timer.
uint8_t IsExpiredTimer (uint32_t *const Timer, const uint32_t Timeout)
Checks if timer timeout has expired.
void Reset_Main_Counter (void)
uint32_t ReadTimer (uint32_t *const Timer)
Detailed Description
Contains clocks and timer functions prototypes.
mikl7.nosp@m.4@ya.nosp@m.hoo.c.nosp@m.om
Version
1.10 Mykhaylo Shcherbak
Macro Definition Documentation
CORE_FREQ
#define CORE_FREQ 8000000
Referenced by Systick_Init().
SYSTICK_FREQ
#define SYSTICK_FREQ 1000
Referenced by Systick_Init().
Typedef Documentation
Systick_Callback_t
typedef void(* Systick_Callback_t) (void)
Function Documentation
Clock_HSI_Init()
void Clock_HSI_Init (void)
inits HSI as a main clock. PLL will not be used. Core/systick frequency is ~8Mhz
Referenced by main().
IsExpiredTimer()
uint8_t IsExpiredTimer (uint32_t *const Timer, const uint32_t Timeout)
Checks if timer timeout has expired.
Parameters
Timer Timer variable
Timeout Timeout value in ms
Returns
zero if timer has not expired, non-zero else
Referenced by Blink_Led(), Buttons_Get_State(), main(), and mainCyclePreRun().
ReadTimer()
uint32_t ReadTimer (uint32_t *const Timer)
Referenced by Control_Outs().
Reset_Main_Counter()
void Reset_Main_Counter (void)
ResetTimer()
void ResetTimer (uint32_t *const Timer)
Resets software timer.
Parameters
Timer timer variable
Referenced by Blink_Led(), Buttons_Get_State(), Control_Outs(), main(), and mainCyclePreRun().
Systick_Init()
void Systick_Init (const Systick_Callback_t Systick_Callback)
Inits systick timer interrupt for 1ms period.
References CORE_FREQ, and SYSTICK_FREQ.
Referenced by main().